### ISSUE TITLE
Not supplying argument to generate, clone, or edit causes runtime panic

### ISSUE THREAD

**Issue by mcmillhj** [ejcx/passgo#13]
When attempting to generate a password using the default length, I noticed a runtime panic from passgo. While looking into this I realized that specifically asking for an element of a slice that does not exist causes failure in Golang, more information [here](http://stackoverflow.com/questions/30302017/golang-command-arguments-empty-causing-error).

Go version 1.6.1
Error message:

```
hunter@eros:~/ownCloud/git/passgo> passgo generate
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x5728e0, 0xc82000e1e0)
	/usr/lib64/go/src/runtime/panic.go:464 +0x3e6
main.main()
	/home/hunter/ownCloud/git/godir/src/github.com/ejcx/passgo/passgo.go:97 +0xf77 
```

the edit and clone commands are also susceptible to this error.

**Comment by ejcx** [comment]
That will be fixed in #4 . I'll test it now and get it merged.

**Comment by mcmillhj** [comment]
Crap, I already wrote a patch for it. I didn't realize it was already fixed.

**Comment by ejcx** [comment]
I think we're good here now. I merged a fix. Thanks @mcmillhj
