### ISSUE TITLE
Restrict naming of sites

### ISSUE THREAD

**Issue by hsson** [ejcx/passgo#16]
When adding sites, some site names should be blacklisted. In particular, if you try to insert a site with the same name as a command. 

For example, generating a site with the name "insert" wouldn't allow the user to ever get the password for that site, since `passgo insert` would invoke the insert command. Of course, the user could solve this by simply renaming the site, but why create the problem from the beginning?

**Comment by ejcx** [comment]
That is hilarious. Good catch.
