### ISSUE TITLE
Any plans to include username?

### ISSUE THREAD

**Issue by imjcham** [ejcx/passgo#18]
Would be nice to include username also along with the password.  Is this a possible feature enhancement?

**Comment by ejcx** [comment]
Yes but no. Not in the very near term because I don't know the best way to present the username. How would you like it to work?

**Comment by dbmlabs** [comment]
Just thinking about it quickly, using passgo insert you would insert the website and it would prompt for username and password.  Then when you run passgo to retrieve the password, it would show up something like this:

./passgo insert example.com 
Enter username for example.com: johndoe
Enter password for example.com: *********

./passgo example.com
Enter master password: ********* 
username: johndoe
password: passw0rd!

**Comment by dncohen** [comment]
How about a `--multiline` option, same as https://www.passwordstore.org/#organization ?

**Comment by ejcx** [comment]
Yes! Multi line is what I wanted but I never got around to building it
