### ISSUE TITLE
passgo init "Could not make initial commit"

### ISSUE THREAD

**Issue by dncohen** [ejcx/passgo#23]
Hey, saw your quick talk at gopherfest!  Giving passgo a try I ran into this:

```
[user@sandbox ~]$ go get github.com/ejcx/passgo
[user@sandbox ~]$ which passgo
~/gocode/bin/passgo
[user@sandbox ~]$ passgo init
Please enter a strong master password: 
2016/05/17 04:24:53 Could not make initial commit: exit status 128
```

Despite the error, passgo appears to be working.

```
[user@sandbox ~]$ passgo insert test/first
Enter password for test/first: 
[user@sandbox ~]$ passgo
.
└──test
   └──first
```

Lastly, a thought unrelated to the error message (I think).  Strong crypto or not, there's no reason for .passgo or its contents to be world-readable.

```
[user@sandbox ~]$ ls -la .passgo/
total 20
drwxr-xr-x  3 user user 4096 May 17 04:24 .
drwx------ 30 user user 4096 May 17 04:24 ..
-rw-rw-r--  1 user user  724 May 17 04:24 config
drwxrwxr-x  7 user user 4096 May 17 04:31 .git
-rw-rw-r--  1 user user  227 May 17 04:31 sites.json
```

Lastly (for real), thanks for contributing this!

**Comment by ejcx** [comment]
Thanks, I appreciate it!

I should add in the documentation that passgo needs git installed. That's how the backend syncing works.

You're right. The general threatmodel for ALL password managers is once an attacker is on your machine you are toast. I can definitely scope down the permissions though to the files are not 755 and instead are 700.

**Comment by dncohen** [comment]
So you know, it is not that `git` is not installed.  You'll see in the description above, `.git` was created.

```
[user@sandbox ~]$ which git
/usr/bin/git
[user@sandbox ~]$ git --version
git version 2.5.5
[user@sandbox ~]$ uname -a
Linux sandbox 4.2.8-8.pvops.qubes.x86_64 #1 SMP Tue Jan 5 03:04:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[user@sandbox ~]$ 
```

It's a interesting choice to use git.  I see the benefits of having history, and using a remote to sync passwords.  However it adds weight to the tool.  Personally I won't be using github to sync my passwords.  I could see using `syncthing` or something like it.  If `passgo` had the option of storing each password in its own file, I might choose that over git.

**Comment by ejcx** [comment]
Ah I didn't examine the output that you gave me fully. That's more of a mystery of you have git installed

If you don't want to sync your passwords with git to a private repo or git server you own then I can't help you unfortunately. You don't have to use GitHub and are free to set whatever remote pleases you.

**Comment by rsommerard** [comment]
Hi, I had the same problem. 
I solved it by setting the global git configurations:

- `git config --global user.email "you@example.com"`
- `git config --global user.name "Your Name"`

**Comment by shurcooL** [comment]
> I should add in the documentation that passgo needs git installed. That's how the backend syncing works.

You can also check in code with something like:

```Go
if _, err := exec.LookPath("git"); err != nil {
	fmt.Fprintln(os.Stderr, "`git` command is required for this command to work.")
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
```
