### ISSUE TITLE
Usability issue with retrieving passwords and proposed fix.

### ISSUE THREAD

**Issue by shurcooL** [ejcx/passgo#32]
Hi again. I've started using and relying on `passgo` recently, I really like it, and I'd like to contribute to try to make it even better.

When I first tried it, I had to learn the CLI and how to use it, and I ran into a pretty glaring IMO usability issue. I will explain it here, and also propose a fix.

## Usability Issue

passgo has quite a few commands:

https://github.com/ejcx/passgo#commands

And it's described as:

> stores, retrieves, generates, and synchronizes passwords securely and is written in Go!

So it's pretty clear and *storing* and *retrieving* passwords is the core functionality.

Yet when I tried to read about the commands it has in https://github.com/ejcx/passgo#commands, I was only able to find a command to *store* a password:

https://github.com/ejcx/passgo#passgo-insert-grouppass-name

```
passgo insert group/pass-name
```

I looked really really hard and literally spent 10 minutes trying to figure out how to *retrieve* a password, but it was not documented anywhere at all. I thought it was really surprising given how it's such basic functionality.

After 10 mins of reading the README, trying stuff and looking at the source code, I was eventually able to figure it out, to retrieve the password, there is no command, you just need to type:

```
passgo group/pass-name
```

But this is literally not documented anywhere!

## Proposed Fix

A very basic fix is to document how to retrieve the password and add it to the README, together with all the other commands that are already documented there.

However, I'd like to propose a slightly different solution.

I think it's a bad idea to not have an explicit command name for something as fundamental as retrieving the password. It's unintuitive, inconsistent, asymmetrical, and makes it hard to document the command. It also has the danger of overlapping with an existing command name (see #16). You can accidentally try to fetch a password for a site called "push" and inadvertently perform an unwanted action.

I think a really good solution would be to add an explicit command for retrieving passwords. That resolves all the issues above with not having a proper command.

What do you think?

**Comment by ejcx** [comment]
Hey @shurcooL, I'm super glad you're using passgo and I would love to help you get the use out of it that you want.

Do you have a specific subcommand name to recommend? This "no command" was copied from https://www.passwordstore.org/ ?

I could live with `show`, since it already lives in the show package.

**Comment by shurcooL** [comment]
I was considering `get`, but `show` works too.

**Comment by ejcx** [comment]
Just merged. Going to close. Thanks @shurcooL

**Comment by shurcooL** [comment]
Thank you!
