### ISSUE TITLE
-copy working?

### ISSUE THREAD

**Issue by dncohen** [ejcx/passgo#34]
Can you provide an example of `passgo show` with -copy flag?

I see the commit with this logic, but I'm unable to put the right command together.  It's not in the usage or readme, does it work yet?

Thanks!

**Comment by ejcx** [comment]
I'll check it out and get back to you. Thanks.

**Comment by ejcx** [comment]
Nice catch. Found the bug. Will fix it with another PR I'm making shortly

**Comment by ejcx** [comment]
Should be fixed in #36

**Comment by ejcx** [comment]
Should work now!

**Comment by dncohen** [comment]
Glad to see #36, the files feature looks great.

Congrats on v1.0, btw.  I recommend a v1.0 tag (or 1.0.0 for semver).
