### ISSUE TITLE
insertfile command creates a "files" directory, but doesn't include it in commit.

### ISSUE THREAD

**Issue by dmitshur** [ejcx/passgo#49]
Reproduce steps:

1. cd into ~/.passgo and `git status`, note that it's clean
2. use `passgo insertsite ...`
3. do `git status`, see:

    ```
    On branch master
    Untracked files:
      (use "git add <file>..." to include in what will be committed)

    	files/
    
    nothing added to commit but untracked files present (use "git add" to track)
    ```

I suspect it's because `git add -u` is used to stage files in `sync.Commit`:

https://github.com/ejcx/passgo/blob/1689ac6a1fd02081099f45d45764ace200e41c29/sync/sync.go#L216

Perhaps `git add -A` would be more appropriate?

**Comment by ejcx** [comment]
Good catch! Thanks for the report.
