### ISSUE TITLE
generate: Sometimes generates longer passwords than asked.

### ISSUE THREAD

**Issue by dmitshur** [ejcx/passgo#52]
`passgo generate` help says:

	passgo generate length=24
		Prints a randomly generated password. The length of this password defaults
		to 24. If a very short length is specified, the generated password will be
		longer than desired and will contain a upper-case, lower-case, symbol, and
		digit.

I've noticed that running `passgo generate` sometimes generates passwords with greater than 24 length. I've gotten: 25, 32, 37, 39.

It happens with the default `passgo generate` invocation, but also for other values of length. E.g., when I ran `passgo generate 20` a bunch of times, I got lengths like: 24, 25, 32.

To reproduce, run `go generate` at least 20-30 times.

Is this a bug or intentional behavior which isn't documented?

**Comment by dmitshur** [comment]
After reading the [`pc.GeneratePassword`](https://github.com/ejcx/passgo/blob/833999f9aa7e85c20c99a1c3615f0a7f7d5c3429/pc/pc.go#L193-L229) code, I suspect I understand what's happening.

It keeps appending to the password until it reaches the requested length, and also has all the required letters:

```
// It requires generation of a string password that has a upper case
// letter, a lower case letter, a symbol, and a number.
```

So in some rare cases, a password of length 24 doesn't yet satisfy all those requirements, so it becomes longer.

Ironically, this _is_ documented here:

	If a very short length is specified, the generated password will be
	longer than desired and will contain a upper-case, lower-case, symbol, and
	digit.

I just didn't think that applied because I didn't consider 24 to be a "very short length". Maybe it'd be good to rephrase it as something like:

	The generated password will contain a upper-case, lower-case, symbol,
	and digit, and may end up longer than requested in order to accommodate that.

**Comment by ejcx** [comment]
Yeah @dmitshur, it totally is documented. Maybe I could try generating more than once? Perhaps after 100 generations if it doesn't find a password that meets the requirements, it could return a longer one.

**Comment by ejcx** [comment]
I also really hate that `GeneratePassword` function I wrote.
