### ISSUE TITLE
Version 2 compatibility with version 1?

### ISSUE THREAD

**Issue by dmitshur** [ejcx/passgo#59]
Hi @ejcx. I saw that you've worked on version 2 of passgo in PR #57, and have released it by now.

I'm not finding much in the release notes or README about compatibility with version 1. Usually major version bump represents a breaking change, that's why I'm not sure.

If I've been using passgo 1.x and have a vault it created, can passgo 2.x continue to work with that vault, or do I need to create a new vault and import my passwords into it?

Thanks!

**Comment by ejcx** [comment]
Hey @dmitshur . I don't think it there should be any compatibility issues. I say give it a try and it should "just work"

**Comment by ejcx** [comment]
If you run in to any issues let me know. The main changes:
    - Regular sites are stored as files now by default.
    - Changed the CLI (so if you have scripts using passgo they will need to be updated).

**Comment by dmitshur** [comment]
> I don't think it there should be any compatibility issues.

Great! Thanks for answering.

> -	Regular sites are stored as files now by default.

As opposed to what? How were they stored before?

**Comment by ejcx** [comment]
@dmitshur before they were all in a big json blob in a single file.

Now they are actually saved in separate binary files. It simplified the code quite a bit to treat files and passwords the same, since I added files after v1 was initially released.
