### ISSUE TITLE
motivation for removing password vault git history

### ISSUE THREAD

**Issue by dmitshur** [ejcx/passgo#66]
Hey @ejcx,

I just noticed that passgo v2 no longer uses git to track history of updates to the password vault in `~/.passgo`. I wanted to ask what was the motivation for removing that functionality?

For reference, I never used the push/pull functionality to sync the git repo elsewhere, and figured that could easily be done externally (i.e., it makes sense to make that out of scope), but I enjoyed the git history tracking after each password insert/edit/remove operation. It meant I could worry less about accidentally losing something valuable. This feature seems harder to implement outside of `passgo`.

I'm asking because I'd like to understand this better. Thanks!

**Comment by ejcx** [comment]
Good question. I did it because they way it worked, it was really hacky. I basically had hardcoded a few git commands in to the cli and it didn't handle all the git things properly.

I could potentially add them back and do it the right way I guess, but I felt like it was better to force people to maintain their own git repo than have a bunch of hacky code in the project.

**Comment by dmitshur** [comment]
Thanks for elaborating. That makes sense, it's better not to include a hacky solution that can be considered out of scope, and focus on doing the main task.

I'll take some time to think about whether there's a good way to manage the history of the passgo password vault externally. If there is, that'll be a great outcome, because then the `passgo` command can continue to stay simpler and smaller in scope.

**Comment by ejcx** [comment]
@dmitshur can I close this? From my understanding you were just asking a question, not looking to get this re-implemented in git?

**Comment by dmitshur** [comment]
Yes, this was a question. I think it's answered now, so I'll close. If I think of concrete suggestions, I'll make a new issue. Thanks.
