### ISSUE TITLE
Better syncing error messages based on output

### ISSUE THREAD

**Issue by ejcx** [ejcx/passgo#8]
Right now we are "shelling out" to git commands. This isn't that great but better options are scarce.

Returning error, right now, only gives us opaque failure messages even when things succeed. We can scrape the exec Command Output for patterns that determine if a particular command was successful or not.

For example a successful push ends with something that looks like this.

```
  aaaaaaa..aaaaaaa  master -> master  
```

**Comment by hsson** [comment]
Perhaps [this library](https://github.com/libgit2/git2go) could be of help?

**Comment by ejcx** [comment]
@hsson I looked but it's overly complex. Not for me. I think we can do plenty good without it

**Comment by icyhugs** [comment]
@ejcx is mercurial or other vcs support planned, or is this just purely parsing git messages?

**Comment by ejcx** [comment]
@icyhugs other VCS are not currently supported.

The way syncing works is passgo uses the exec package and runs git command. It isn't pretty but it works. I thought git2go was too complex for what I needed.

I want to understand the error messages and patterns of them to determine what exactly went wrong in the case of failure.
